###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
OPENSSL_DIR="C:\\Program Files\\OpenSSL-Win64"

###################
## Test          ##
###################

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-watch]
command = "cargo"
args = ["watch", "-w", "../../shared/rust", "-w", ".", "-x", "test --features local-quiet -- --nocapture"]

###################
## Dev           ##
###################


[tasks.dev]
command = "systemfd"
args = ["--no-pid", "-s", "http::8082", "--", "cargo", "watch", "-w", "../../shared/rust", "-w", ".", "-x", "run --features local-quiet"]

[tasks.dev-noquiet]
command = "systemfd"
args = ["--no-pid", "-s", "http::8082", "--", "cargo", "watch", "-w", "../../shared/rust", "-w", ".", "-x", "run --features local"]
