###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
DOCKER_BUILDKIT = "1"

###################
## Gcloud        ##
###################

[tasks.gcloud-configure-docker]
script_runner = "@shell"
script = ["gcloud auth configure-docker"]

###################
## PAGES         ##
###################

#------Release-----------#
[tasks.release-pages]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-release-pages",
    "docker-publish-release-pages",
    "deploy-release-pages",
]}]

[tasks.docker-build-release-pages]
command = "docker"
args = ["build", "-f", "backend/pages/Dockerfile", "--target", "release", "-t", "gcr.io/ji-cloud/ji-cloud-pages:latest", "."]

[tasks.docker-publish-release-pages]
command = "docker"
args = ["push", "gcr.io/ji-cloud/ji-cloud-pages:latest"]

[tasks.deploy-release-pages]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-pages --project ji-cloud --region europe-west2 --image gcr.io/ji-cloud/ji-cloud-pages:latest --platform managed"]

#------Sandbox-----------#
[tasks.sandbox-pages]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-sandbox-pages",
    "docker-publish-sandbox-pages",
    "deploy-sandbox-pages",
]}]

[tasks.docker-build-sandbox-pages]
command = "docker"
args = ["build", "-f", "backend/pages/Dockerfile", "--target", "sandbox", "-t", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-pages-sandbox:latest", "."]

[tasks.docker-publish-sandbox-pages]
command = "docker"
args = ["push", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-pages-sandbox:latest"]

[tasks.deploy-sandbox-pages]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-pages-sandbox --project ji-cloud-developer-sandbox --region europe-west2 --image gcr.io/ji-cloud-developer-sandbox/ji-cloud-pages-sandbox:latest --platform managed"]

###################
## API           ##
###################

#------Release-----------#
[tasks.release-api]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-release-api",
    "docker-publish-release-api",
    "deploy-release-api",
]}]

[tasks.docker-build-release-api]
command = "docker"
args = ["build", "-f", "backend/api/Dockerfile", "--target", "release", "-t", "gcr.io/ji-cloud/ji-cloud-api:latest", "."]

[tasks.docker-publish-release-api]
command = "docker"
args = ["push", "gcr.io/ji-cloud/ji-cloud-api:latest"]

[tasks.deploy-release-api]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-api --project ji-cloud --region europe-west2 --image gcr.io/ji-cloud/ji-cloud-api:latest --platform managed"]

#------Sandbox-----------#
[tasks.sandbox-api]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-sandbox-api",
    "docker-publish-sandbox-api",
    "deploy-sandbox-api",
]}]

[tasks.docker-build-sandbox-api]
command = "docker"
args = ["build", "-f", "backend/api/Dockerfile", "--target", "sandbox", "-t", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-sandbox:latest", "."]

[tasks.docker-publish-sandbox-api]
command = "docker"
args = ["push", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-sandbox:latest"]

[tasks.deploy-sandbox-api]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-api-sandbox --project ji-cloud-developer-sandbox --region europe-west2 --image gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-sandbox:latest --platform managed"]

###################
## API-JS        ##
###################

#------Release-----------#
[tasks.release-api-js]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-release-api-js",
    "docker-publish-release-api-js",
    "deploy-release-api-js",
]}]

[tasks.docker-build-release-api-js]
command = "docker"
args = ["build", "-f", "backend/api-js/Dockerfile", "--target", "release", "-t", "gcr.io/ji-cloud/ji-cloud-api-js:latest", "."]

[tasks.docker-publish-release-api-js]
command = "docker"
args = ["push", "gcr.io/ji-cloud/ji-cloud-api-js:latest"]

[tasks.deploy-release-api-js]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-api-js --project ji-cloud --region europe-west2 --image gcr.io/ji-cloud/ji-cloud-api-js:latest --platform managed"]

#------Sandbox-----------#
[tasks.sandbox-api-js]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-sandbox-api-js",
    "docker-publish-sandbox-api-js",
    "deploy-sandbox-api-js",
]}]

[tasks.docker-build-sandbox-api-js]
command = "docker"
args = ["build", "-f", "backend/api-js/Dockerfile", "--target", "sandbox", "-t", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-js-sandbox:latest", "."]

[tasks.docker-publish-sandbox-api-js]
command = "docker"
args = ["push", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-js-sandbox:latest"]

[tasks.deploy-sandbox-api-js]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-api-js-sandbox --project ji-cloud-developer-sandbox --region europe-west2 --image gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-js-sandbox:latest --platform managed"]
