[package]
name = "shared"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"
description = "shared types for ji cloud project"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_repr = "^0.1"
serde_json = "^1.0"
cfg-if = "^0.1"
