[package]
name = "ji_cloud_shared"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"
description = "shared types for ji cloud project"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_repr = "^0.1"
strum = "^0.18"
strum_macros = "^0.18"
log = "^0.4"
wasm-bindgen = {version = "0.2.62", features=["nightly"], optional = true }
js-sys = {version = "0.3.39", optional = true }
wasm-bindgen-futures = {version = "0.4.12", optional = true }
serde-wasm-bindgen = { version = "0.1.3", optional = true }
serde_json = { version = "^1.0", optional = true }
web-sys = { version = "0.3.39", optional = true}

[features]
default = []
frontend = [
    "wasm-bindgen", 
    "js-sys", 
    "wasm-bindgen-futures", 
    "serde-wasm-bindgen", 
    "serde_json",
    'web-sys/Url',
    'web-sys/Request',
    'web-sys/RequestInit',
    'web-sys/RequestCredentials',
    'web-sys/Response',
    'web-sys/RequestMode',
    'web-sys/Headers',
    'web-sys/Window',
    'web-sys/Location',
    'web-sys/Storage'
]

backend = ["serde_json"]
