###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
DOCKER_BUILDKIT = "1"

###################
## Database      ##
###################

[tasks.db-local]
command = "docker-compose"
args = ["up", "-d", "db"]
