###################
## Config        ##
###################

[config]
skip_core_tasks = true
default_to_workspace = false

[env]
DOCKER_BUILDKIT = "1"
CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true

env_files = ["../../.env"]

[tasks.local-port-main]
script_runner = "@duckscript"
script = '''
set_env APP_PORT 4104 
'''

[tasks.local-port-iframe]
script_runner = "@duckscript"
script = '''
set_env APP_PORT 4105 
'''

##########################
## SCRATCH APPLICATIONS ##
##########################

[tasks.scratch-001]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "scratch/001" 
cm_run_task local-main
'''

###################
## APPLICATIONS  ##
###################

# USER
[tasks.user-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task local-main
'''
# USER
[tasks.user-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task local-main-nomedia
'''

[tasks.user-local-iframe]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task local-iframe

'''
[tasks.user-local-iframe-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task local-iframe-nomedia
'''

[tasks.user-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task sandbox 
'''

[tasks.user-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task release 
'''

# ADMIN 
[tasks.admin-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME admin
cm_run_task local-main
'''

[tasks.admin-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME admin
cm_run_task local-main-nomedia
'''

[tasks.admin-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME admin 
cm_run_task sandbox 
'''

[tasks.admin-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME admin 
cm_run_task release 
'''

# JIG - SHELL 
[tasks.jig-edit-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/edit" 
cm_run_task local-main
'''

[tasks.jig-edit-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/edit" 
cm_run_task local-main-nomedia
'''

[tasks.jig-edit-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/edit" 
cm_run_task sandbox 
'''

[tasks.jig-edit-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/edit" 
cm_run_task release 
'''


[tasks.jig-play-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/play" 
cm_run_task local-iframe
'''

[tasks.jig-play-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/play" 
cm_run_task local-iframe-nomedia
'''

[tasks.jig-play-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/play" 
cm_run_task sandbox 
'''

[tasks.jig-play-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "jig/play" 
cm_run_task release 
'''

#######################
## MODULES           ##
#######################

# MODULE - MEMORY
[tasks.module-memory-edit-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/edit" 
cm_run_task local-main
'''

[tasks.module-memory-edit-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/edit" 
cm_run_task local-main-nomedia
'''

[tasks.module-memory-edit-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/edit" 
cm_run_task sandbox 
'''

[tasks.module-memory-edit-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/edit" 
cm_run_task release 
'''


[tasks.module-memory-play-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/play" 
cm_run_task local-iframe
'''

[tasks.module-memory-play-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/play" 
cm_run_task local-iframe-nomedia
'''

[tasks.module-memory-play-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/play" 
cm_run_task sandbox 
'''

[tasks.module-memory-play-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/memory/play" 
cm_run_task release 
'''

# MODULE - POSTER 
[tasks.module-poster-edit-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/poster/edit" 
cm_run_task local-main
'''

[tasks.module-poster-edit-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/poster/edit" 
cm_run_task local-main-nomedia
'''

[tasks.module-poster-edit-sandbox]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/poster/edit" 
cm_run_task sandbox 
'''

[tasks.module-poster-edit-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/poster/edit" 
cm_run_task release 
'''


[tasks.module-poster-play-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/poster/play" 
cm_run_task local-iframe
'''

[tasks.module-poster-play-local-nomedia]
script_runner = "@duckscript"
script = '''
set_env APP_NAME "module/poster/play" 
cm_run_task local-iframe-nomedia
'''




#######################
## COMMON            ##
#######################
[tasks.clean-templates]
script_runner = "@duckscript"
script = '''
rm -rf ../.template_output
'''

#######################
## BUILD - SANDBOX ##
#######################
[tasks.sandbox]
run_task = {name = [
    "clean-templates",
    "sandbox-build-templates",
    "sandbox-build-app",
]}

[tasks.sandbox-build-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "sandbox"]
cwd = "../build-utils/templates-builder"


[tasks.sandbox-build-app]
script_runner = "@shell"
script = ["npm run build:sandbox"]

#######################
## BUILD - RELEASE   ##
#######################
[tasks.release]
run_task = {name = [
    "clean-templates",
    "release-build-templates",
    "release-build-app",
]}

[tasks.release-build-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "release"]
cwd = "../build-utils/templates-builder"


[tasks.release-build-app]
script_runner = "@shell"
script = ["npm run build:release"]

###################
## local ##
###################
[tasks.local-main]
run_task = {name = [
    "clean-templates",
    "local-port-main",
    "local-build-templates",
    "local-prep-files",
    "local-start",
]}

[tasks.local-iframe]
run_task = {name = [
    "clean-templates",
    "local-port-iframe",
    "local-build-templates",
    "local-prep-files",
    "local-start",
]}

[tasks.local-main-nomedia]
run_task = {name = [
    "local-port-main",
    "local-prep-files",
    "local-watch-app",
]}

[tasks.local-iframe-nomedia]
run_task = {name = [
    "local-port-iframe",
    "local-prep-files",
    "local-watch-app",
]}

[tasks.local-prep-files]
script_runner = "@shell"
script = ["npm run local-dev-files"]
cwd = "../build-utils"

[tasks.local-build-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "local"]
cwd = "../build-utils/templates-builder"

[tasks.local-start]
run_task = { name = [
    "local-start-mediaserver",
    "local-watch-css-tailwind",
    "local-watch-css-plain",
    "local-watch-templates",
    "local-watch-app",
], fork = true, parallel = true }

[tasks.local-start-mediaserver]
script_runner = "@shell"
script = ["npm run local-media-server"]
cwd = "../build-utils"

# running watch from npm is not working for some reason
# so redefining it below

[tasks.local-watch-css-plain]
command = "watchexec"
args = ["-w", "src", "npm run bundle:prod"]
cwd = "../css/plain"

[tasks.local-watch-css-tailwind]
command = "watchexec"
args = ["-w", "src", "-w", "../../.template_output", "npm run bundle:prod"]
cwd = "../css/tailwind"

[tasks.local-watch-templates]
command = "cargo"
args = ["run", "--", "--remote-target", "local"]
cwd = "../build-utils/templates-builder"
watch = { watch = ["../templates"] }

[tasks.local-watch-app]
script_runner = "@shell"
script = ["npm run build:watch"]
