###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
OPENSSL_DIR="C:\\Program Files\\OpenSSL-Win64"

###################
## Test          ##
###################

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-watch]
command = "cargo"
args = ["watch", "-w", "../../shared/rust", "-w", ".", "-x", "test --features local-quiet -- --nocapture"]

###################
## Run 		 ##
###################

[tasks.migrate-local]
command = "cargo"
args = ["run", "--", "--target", "local", "--verbose"]


[tasks.migrate-sandbox]
run_task = { name = [ "google-sql-proxy-sandbox", "run-proxy-sandbox", ], parallel = true }

[tasks.migrate-release]
run_task = { name = [ "google-sql-proxy-release", "run-proxy-release", ], parallel = true }

[tasks.connection_string-local]
command = "cargo"
args = ["run", "--", "--target", "local", "--connection-string-only"]

[tasks.connection_string-sandbox]
command = "cargo"
args = ["run", "--", "--target", "sandbox", "--connection-string-only"]

[tasks.connection_string-release]
command = "cargo"
args = ["run", "--", "--target", "release", "--connection-string-only"]
## Sub tasks

[tasks.run-proxy-sandbox]
command = "cargo"
args = ["run", "--", "--target", "sandbox", "--verbose"]

[tasks.run-proxy-release]
command = "cargo"
args = ["run", "--", "--target", "release", "--verbose"]

[tasks.google-sql-proxy-sandbox]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = ["cd ../","npm run cloud-sql-proxy-sandbox"]

[tasks.google-sql-proxy-release]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = ["cd ../","npm run cloud-sql-proxy-release"]
