name: Admin - CSS - Release

on:
  push:
    branches: [ master ]
    paths:
    - 'frontend/_core/css/**'
    - 'frontend/admin/css/**'

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE

      - name: checkout repo
        uses: actions/checkout@v1

      - name: Extract label 
        shell: bash
        run: echo "##[set-output name=label;]$(echo \"[${GITHUB_REF#refs/heads/} - admin/css]\")"
        id: extract_label

      - name: Notify slack
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} starting...\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: install node
        uses: actions/setup-node@v1

      - name: install npm deps
        run: npm install
        working-directory: "./frontend/admin/css"

      - name: bundle 
        run: npm run bundle
        working-directory: "./frontend/admin/css"

      - name: install google cloud sdk
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '295.0.0'
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY }}

      - name: deploy to google cloud
        run: gsutil -m rsync -d -r frontend/admin/css/dist gs://ji-cloud-frontend-origin-eu-001/admin/css

      - name: Notify slack of all status
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} ${{job.status}}\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
