name: Documentation - Book

on:
  push:
    branches: [ sandbox ]
    paths:
    - 'config/**'
    - 'documentation/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Extract label 
      shell: bash
      run: echo "##[set-output name=label;]$(echo \"[${GITHUB_REF#refs/heads/} - documentation]\")"
      id: extract_label

    - name: Notify slack
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} starting...\"}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    - name: install mdbook 
      run: cargo install mdbook 

    - name: build documentation
      run: mdbook build
      working-directory: ./documentation

    - name: install google cloud sdk
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '295.0.0'
        service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY_SANDBOX }}

    - name: deploy to google cloud
      run: gsutil -m rsync -d -r documentation/output gs://ji-cloud-sandbox-docs-origin-eu-001/book

    - name: Notify slack of all status
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} ${{job.status}}\"}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: always()
